import type {
  Property,
  Tenant,
  Lease,
  Payment,
  WorkOrder,
  ShortletBooking,
  KPIData,
} from "./types";

export const mockKPIs: KPIData = {
  monthlyRevenue: 48200000,
  revenueChange: 12.4,
  occupancyRate: 94.3,
  occupancyChange: 2.1,
  openWorkOrders: 23,
  overdueRent: 3100000,
  totalProperties: 47,
  totalUnits: 312,
  collectionRate: 91.2,
  renewalRate: 78.5,
  activeShortlets: 18,
  shortletRevenue: 6400000,
};

export const mockProperties: Property[] = [
  {
    id: "p1",
    name: "Veethrill Towers",
    type: "MIXED_USE",
    address: "15 Adeola Odeku Street",
    city: "Victoria Island",
    state: "Lagos",
    country: "Nigeria",
    totalUnits: 48,
    occupiedUnits: 48,
    occupancyRate: 100,
    monthlyRevenue: 14800000,
    status: "ACTIVE",
    healthScore: 96,
    createdAt: "2022-01-15",
  },
  {
    id: "p2",
    name: "Abuja Central Plaza",
    type: "COMMERCIAL",
    address: "Plot 3, Aminu Kano Crescent",
    city: "Wuse II",
    state: "FCT",
    country: "Nigeria",
    totalUnits: 32,
    occupiedUnits: 31,
    occupancyRate: 96.9,
    monthlyRevenue: 9600000,
    status: "ACTIVE",
    healthScore: 91,
    createdAt: "2021-06-10",
  },
  {
    id: "p3",
    name: "Lekki Gardens Phase 3",
    type: "RESIDENTIAL",
    address: "Admiralty Way",
    city: "Lekki",
    state: "Lagos",
    country: "Nigeria",
    totalUnits: 60,
    occupiedUnits: 53,
    occupancyRate: 88.3,
    monthlyRevenue: 8100000,
    status: "ACTIVE",
    healthScore: 84,
    createdAt: "2023-03-20",
  },
  {
    id: "p4",
    name: "PH Waterfront Estate",
    type: "RESIDENTIAL",
    address: "24 Aba Road",
    city: "GRA Phase 2",
    state: "Rivers",
    country: "Nigeria",
    totalUnits: 24,
    occupiedUnits: 22,
    occupancyRate: 91.7,
    monthlyRevenue: 6300000,
    status: "ACTIVE",
    healthScore: 88,
    createdAt: "2022-09-05",
  },
  {
    id: "p5",
    name: "Ikoyi Pearl Court",
    type: "LUXURY_RESIDENTIAL",
    address: "3 Alexander Road",
    city: "Ikoyi",
    state: "Lagos",
    country: "Nigeria",
    totalUnits: 12,
    occupiedUnits: 10,
    occupancyRate: 83.3,
    monthlyRevenue: 5800000,
    status: "ACTIVE",
    healthScore: 79,
    createdAt: "2020-11-30",
  },
  {
    id: "p6",
    name: "Lekki Shortlet Suites",
    type: "SHORTLET",
    address: "5 Freedom Way",
    city: "Lekki Phase 1",
    state: "Lagos",
    country: "Nigeria",
    totalUnits: 20,
    occupiedUnits: 18,
    occupancyRate: 90,
    monthlyRevenue: 6400000,
    status: "ACTIVE",
    healthScore: 93,
    createdAt: "2024-01-10",
  },
  {
    id: "p7",
    name: "Gwarinpa Executive Suites",
    type: "RESIDENTIAL",
    address: "Block C, 1st Avenue",
    city: "Gwarinpa",
    state: "FCT",
    country: "Nigeria",
    totalUnits: 40,
    occupiedUnits: 38,
    occupancyRate: 95,
    monthlyRevenue: 3600000,
    status: "ACTIVE",
    healthScore: 90,
    createdAt: "2021-04-18",
  },
];

export const mockTenants: Tenant[] = [
  {
    id: "t1",
    firstName: "Chidi",
    lastName: "Okafor",
    email: "chidi.okafor@email.com",
    phone: "+234 801 234 5678",
    unitId: "u1",
    unitNumber: "7C",
    propertyName: "Veethrill Towers",
    leaseEnd: "2026-12-31",
    monthlyRent: 350000,
    paymentStatus: "PAID",
    kycStatus: "VERIFIED",
    createdAt: "2025-01-15",
  },
  {
    id: "t2",
    firstName: "Ngozi",
    lastName: "Adeyemi",
    email: "ngozi.adeyemi@email.com",
    phone: "+234 802 345 6789",
    unitId: "u2",
    unitNumber: "3A",
    propertyName: "Lekki Gardens Phase 3",
    leaseEnd: "2028-06-30",
    monthlyRent: 180000,
    paymentStatus: "PAID",
    kycStatus: "VERIFIED",
    createdAt: "2024-06-20",
  },
  {
    id: "t3",
    firstName: "Emeka",
    lastName: "Bello",
    email: "emeka.bello@email.com",
    phone: "+234 803 456 7890",
    unitId: "u3",
    unitNumber: "5B",
    propertyName: "Abuja Central Plaza",
    leaseEnd: "2027-05-31",
    monthlyRent: 250000,
    paymentStatus: "PENDING",
    kycStatus: "PENDING",
    createdAt: "2026-07-01",
  },
  {
    id: "t4",
    firstName: "Fatima",
    lastName: "Ibrahim",
    email: "fatima.ibrahim@email.com",
    phone: "+234 804 567 8901",
    unitId: "u4",
    unitNumber: "2D",
    propertyName: "Veethrill Towers",
    leaseEnd: "2027-03-31",
    monthlyRent: 420000,
    paymentStatus: "OVERDUE",
    kycStatus: "VERIFIED",
    createdAt: "2024-03-10",
  },
  {
    id: "t5",
    firstName: "James",
    lastName: "Oduya",
    email: "james.oduya@email.com",
    phone: "+234 805 678 9012",
    unitId: "u5",
    unitNumber: "1B",
    propertyName: "PH Waterfront Estate",
    leaseEnd: "2026-06-30",
    monthlyRent: 220000,
    paymentStatus: "PAID",
    kycStatus: "VERIFIED",
    createdAt: "2024-07-01",
  },
  {
    id: "t6",
    firstName: "Amara",
    lastName: "Eze",
    email: "amara.eze@email.com",
    phone: "+234 806 789 0123",
    unitId: "u6",
    unitNumber: "4F",
    propertyName: "Ikoyi Pearl Court",
    leaseEnd: "2027-09-30",
    monthlyRent: 580000,
    paymentStatus: "PAID",
    kycStatus: "VERIFIED",
    createdAt: "2025-09-15",
  },
];

export const mockLeases: Lease[] = [
  {
    id: "l1",
    tenantId: "t1",
    tenantName: "Chidi Okafor",
    unitId: "u1",
    unitNumber: "7C",
    propertyName: "Veethrill Towers",
    startDate: "2025-01-01",
    endDate: "2026-12-31",
    rentAmount: 350000,
    depositAmount: 700000,
    status: "ACTIVE",
    autoRenew: true,
  },
  {
    id: "l2",
    tenantId: "t2",
    tenantName: "Ngozi Adeyemi",
    unitId: "u2",
    unitNumber: "3A",
    propertyName: "Lekki Gardens Phase 3",
    startDate: "2026-06-01",
    endDate: "2028-06-30",
    rentAmount: 180000,
    depositAmount: 360000,
    status: "RENEWED",
    autoRenew: false,
  },
  {
    id: "l3",
    tenantId: "t5",
    tenantName: "James Oduya",
    unitId: "u5",
    unitNumber: "1B",
    propertyName: "PH Waterfront Estate",
    startDate: "2024-07-01",
    endDate: "2026-06-30",
    rentAmount: 220000,
    depositAmount: 440000,
    status: "EXPIRED",
    autoRenew: false,
  },
];

export const mockPayments: Payment[] = [
  {
    id: "pay1",
    tenantId: "t1",
    tenantName: "Chidi Okafor",
    leaseId: "l1",
    unitNumber: "7C",
    propertyName: "Veethrill Towers",
    amount: 350000,
    type: "RENT",
    method: "PAYSTACK",
    status: "PAID",
    reference: "PAY-2026-07-001",
    paidAt: "2026-07-02T10:30:00Z",
    dueDate: "2026-07-01",
  },
  {
    id: "pay2",
    tenantId: "t2",
    tenantName: "Ngozi Adeyemi",
    leaseId: "l2",
    unitNumber: "3A",
    propertyName: "Lekki Gardens Phase 3",
    amount: 180000,
    type: "RENT",
    method: "BANK_TRANSFER",
    status: "PAID",
    reference: "PAY-2026-07-002",
    paidAt: "2026-07-01T09:15:00Z",
    dueDate: "2026-07-01",
  },
  {
    id: "pay3",
    tenantId: "t4",
    tenantName: "Fatima Ibrahim",
    leaseId: "l4",
    unitNumber: "2D",
    propertyName: "Veethrill Towers",
    amount: 420000,
    type: "RENT",
    method: "PAYSTACK",
    status: "OVERDUE",
    reference: "PAY-2026-07-004",
    dueDate: "2026-07-01",
  },
];

export const mockWorkOrders: WorkOrder[] = [
  {
    id: "wo1",
    title: "AC unit complete failure",
    description: "Air conditioning unit in Unit 4B has stopped working completely.",
    propertyId: "p1",
    propertyName: "Veethrill Towers",
    unitId: "u8",
    unitNumber: "4B",
    category: "HVAC",
    priority: "URGENT",
    status: "IN_PROGRESS",
    assignedVendorName: "Tunde Electricals",
    estimatedCost: 85000,
    slaHours: 4,
    raisedAt: "2026-07-15T10:00:00Z",
    photos: [],
  },
  {
    id: "wo2",
    title: "Plumbing leak — bathroom",
    description: "Water leaking from ceiling in Unit 12A bathroom.",
    propertyId: "p3",
    propertyName: "Lekki Gardens Phase 3",
    unitId: "u20",
    unitNumber: "12A",
    category: "PLUMBING",
    priority: "HIGH",
    status: "ASSIGNED",
    assignedVendorName: "AquaFix Ltd",
    estimatedCost: 45000,
    slaHours: 8,
    raisedAt: "2026-07-15T07:00:00Z",
    photos: [],
  },
  {
    id: "wo3",
    title: "Elevator annual inspection",
    description: "Scheduled annual safety inspection for Elevator A.",
    propertyId: "p2",
    propertyName: "Abuja Central Plaza",
    category: "INSPECTION",
    priority: "MEDIUM",
    status: "ASSIGNED",
    assignedVendorName: "ElevatorPro NG",
    estimatedCost: 120000,
    slaHours: 72,
    raisedAt: "2026-07-14T09:00:00Z",
    photos: [],
  },
  {
    id: "wo4",
    title: "Common area painting",
    description: "Repaint lobby and corridors in all 3 floors.",
    propertyId: "p4",
    propertyName: "PH Waterfront Estate",
    category: "PAINTING",
    priority: "LOW",
    status: "OPEN",
    slaHours: 168,
    raisedAt: "2026-07-12T11:00:00Z",
    photos: [],
  },
  {
    id: "wo5",
    title: "Generator service — 6 month",
    description: "6-month scheduled maintenance for Block B generator.",
    propertyId: "p3",
    propertyName: "Lekki Gardens Phase 3",
    category: "ELECTRICAL",
    priority: "ROUTINE",
    status: "ASSIGNED",
    assignedVendorName: "PowerTech Services",
    estimatedCost: 65000,
    slaHours: 336,
    raisedAt: "2026-07-08T14:00:00Z",
    photos: [],
  },
];

export const mockShortletBookings: ShortletBooking[] = [
  {
    id: "sb1",
    guestName: "Tunde Fashola",
    guestEmail: "tunde.f@gmail.com",
    guestPhone: "+234 808 111 2222",
    unitId: "su1",
    unitNumber: "Suite 1A",
    propertyName: "Lekki Shortlet Suites",
    checkIn: "2026-07-16",
    checkOut: "2026-07-20",
    nights: 4,
    nightlyRate: 45000,
    totalAmount: 180000,
    source: "DIRECT",
    status: "CONFIRMED",
    guestCount: 2,
  },
  {
    id: "sb2",
    guestName: "Sarah Johnson",
    guestEmail: "sarah.j@outlook.com",
    guestPhone: "+1 555 234 5678",
    unitId: "su2",
    unitNumber: "Suite 2B",
    propertyName: "Lekki Shortlet Suites",
    checkIn: "2026-07-15",
    checkOut: "2026-07-17",
    nights: 2,
    nightlyRate: 55000,
    totalAmount: 110000,
    source: "AIRBNB",
    status: "CHECKED_IN",
    guestCount: 1,
    specialRequests: "Early check-in requested",
  },
  {
    id: "sb3",
    guestName: "Biodun Adewale",
    guestEmail: "biodun@company.ng",
    guestPhone: "+234 809 333 4444",
    unitId: "su3",
    unitNumber: "Suite 3C",
    propertyName: "Lekki Shortlet Suites",
    checkIn: "2026-07-18",
    checkOut: "2026-07-25",
    nights: 7,
    nightlyRate: 42000,
    totalAmount: 294000,
    source: "BOOKING_COM",
    status: "CONFIRMED",
    guestCount: 4,
  },
  {
    id: "sb4",
    guestName: "Claire Dubois",
    guestEmail: "claire.d@yahoo.fr",
    guestPhone: "+33 6 12 34 56 78",
    unitId: "su4",
    unitNumber: "Suite 4D",
    propertyName: "Lekki Shortlet Suites",
    checkIn: "2026-07-10",
    checkOut: "2026-07-15",
    nights: 5,
    nightlyRate: 50000,
    totalAmount: 250000,
    source: "EXPEDIA",
    status: "CHECKED_OUT",
    guestCount: 2,
  },
];

export const revenueChartData = [
  { month: "Jan", revenue: 32000000, target: 35000000 },
  { month: "Feb", revenue: 35500000, target: 36000000 },
  { month: "Mar", revenue: 38200000, target: 38000000 },
  { month: "Apr", revenue: 41000000, target: 40000000 },
  { month: "May", revenue: 44700000, target: 43000000 },
  { month: "Jun", revenue: 48200000, target: 45000000 },
];

export const occupancyTrendData = [
  { month: "Jan", rate: 88 },
  { month: "Feb", rate: 89.5 },
  { month: "Mar", rate: 91 },
  { month: "Apr", rate: 92.2 },
  { month: "May", rate: 93.1 },
  { month: "Jun", rate: 94.3 },
];
